apiVersion: v1
kind: Pod
metadata:
  name: app-sec-kff3345
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command:
    - sleep
    - "4800"
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
