apiVersion: v1
kind: Pod
metadata:
  name: app-sec-kff3345
spec:
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    imagePullPolicy: Always
    name: ubuntu
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-g2xck
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: node01
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-g2xck
    secret:
      defaultMode: 420
      secretName: default-token-g2xck
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2020-03-21T16:44:40Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2020-03-21T16:44:46Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2020-03-21T16:44:40Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://4c6835b9a3e1f35a435d2f17f91093138752ed95fa91af64508dc54c4bcec827
    image: ubuntu:latest
    imageID: docker-pullable://ubuntu@sha256:bec5a2727be7fff3d308193cfde3491f8fba1a2ba392b7546b43a051853a341d
    lastState: {}
    name: ubuntu
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2020-03-21T16:44:45Z
  hostIP: 172.17.0.33
  phase: Running
  podIP: 10.40.0.13
  qosClass: BestEffort
  startTime: 2020-03-21T16:44:40Z
