apiVersion: v1
kind: Service
metadata:
  labels:
    app: messaging-service
  name: messaging-service
  namespace: marketing
spec:
  ports:
  - name: http
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis-pod
  type: ClusterIP
