apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: throw-dice-cronjob
spec:
  schedule: "*/1 * * * *"
  backoffLimit: 25
  jobTemplate:
    spec:
      containers:
      - image: kodekloud/throw-dice
        name: throw-dice
        command: ["shuf -i 1-6 -n 1"]
      restartPolicy: Never
