apiVersion: v1
kind: Pod
metadata:
  labels:
    run: time-check
  name: time-check
  namespace: dvl1987
spec:
  containers:
  - image: busybox
    name: time-check
    resources: {}
    volumeMounts:
    - mountPath: /opt/time
      name: log
    env:
    - name: TIME_FREQ
      valueFrom:
        configMapKeyRef:
          name: time-config
          key: TIME_FREQ
    command: ["/bin/sh"]
    args: ["-c", "while true; do date; sleep $(TIME_FREQ);done"]
  volumes:
  - name: log
    emptyDir: {}
