apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress-mysql
  name: wordpress-mysql
spec:
  ports:
  - name: db-port
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
